DirectoryPath: "dist"
EnforceHTTPS: true
IgnoreURLs:
  - "/api/*"
CheckLinks: true
CheckImages: true
CheckScripts: true
CheckGeneric: true
CheckExternal: true
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreDirectoryMissingTrailingSlash: true
